# Mathematical operations in Numpy


np.mean() – Compute the mean (average) of an array.

np.mean(arr)

np.std() – Compute the standard deviation of an array.

np.std(arr)

np.var() – Compute the variance of an array.

np.var(arr)

np.min() – Compute the minimum value of an array.

np.min(arr)

np.max() – Compute the maximum value of an array.

np.max(arr)

np.sum() – Compute the sum of all elements in an array.

np.sum(arr)

np.prod() – Compute the product of all elements in an array.

np.prod(arr)

np.median() – Compute the median of an array.

np.median(arr)

np.percentile() – Compute the percentile of an array.

np.percentile(arr, 50)  # For the 50th percentile (median)

np.argmin() – Return the index of the minimum value in an array.

np.argmin(arr)

np.argmax() – Return the index of the maximum value in an array.

np.argmax(arr)

np.corrcoef() – Compute the correlation coefficient matrix of two arrays.

np.corrcoef(arr1, arr2)

np.unique() – Find the unique elements of an array.

np.unique(arr)

np.diff() – Compute the n-th differences of an array.

np.diff(arr)

np.cumsum() – Compute the cumulative sum of an array.

np.cumsum(arr)

np.linspace() – Create an array with evenly spaced numbers over a specified interval.

np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

np.log() – Compute the natural logarithm of an array.

np.log(arr)

np.exp() – Compute the exponential of an array.

np.exp(arr)

In [2]:
import numpy as np
arr = np.array([3,5,2,33])

In [4]:
np.mean(arr)

np.float64(10.75)

In [6]:
np.min(arr)

np.int64(2)

In [8]:
np.max(arr)

np.int64(33)

In [9]:
np.std(arr)

np.float64(12.891373084353738)

In [10]:
np.var(arr)

np.float64(166.1875)

In [11]:
np.sum(arr)

np.int64(43)

In [12]:
np.prod(arr)

np.int64(990)

In [13]:
np.median(arr)

np.float64(4.0)

In [16]:
np.percentile(arr, 50)

np.float64(4.0)

In [17]:
np.argmax(arr)

np.int64(3)

In [19]:
np.argmin(arr) #return index of minimum element from an array

np.int64(2)

In [20]:
np.corrcoef(arr)

np.float64(1.0)

In [21]:
np.unique(arr)

array([ 2,  3,  5, 33])

In [22]:
np.diff(arr)

array([ 2, -3, 31])

In [23]:
np.cumsum(arr)

array([ 3,  8, 10, 43])

In [24]:
np.log(arr)

array([1.09861229, 1.60943791, 0.69314718, 3.49650756])

In [25]:
np.exp(arr)

array([2.00855369e+01, 1.48413159e+02, 7.38905610e+00, 2.14643580e+14])

In [26]:
np.linspace(1,22,5)

array([ 1.  ,  6.25, 11.5 , 16.75, 22.  ])