In [1]:
import numpy as np
import time

size = 1_000_000
list1 = list(range(size))
arr1 = np.array(list1)

start = time.time()
# Python list (loop-based)
list_squares = [x ** 2 for x in list1]
end = time.time()
print(f"Time it takes to multiply in list : {end - start}")
print(f"squares of {list_squares[0:10]}")
# NumPy (vectorized)
start = time.time()
numpy_squares = arr1 ** 2
print(f"Squares of Numpy array : {numpy_squares[0:10]}")
end = time.time()

print(f"Time it takes to multiply in array : {end - start}")

Time it takes to multiply in list : 0.23999524116516113
squares of [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
Squares of Numpy array : [ 0  1  4  9 16 25 36 49 64 81]
Time it takes to multiply in array : 0.004866361618041992


# Types of Numpy Array
- 1D array in single line
- 2D array in 2 dimension with rows and columns

In [2]:
array1d = np.array([1,2,3,4,5,6,7,8,9,10])
array2d = np.array([[1,2,3,4],[5,6,7,8]])

print(f"Array1d = {array1d}, and size = {array1d.size}\n and shape = {array1d.shape}")

print(f"Array1d = {array1d}, and size = {array1d.size}\n and shape = {array2d.shape}")

Array1d = [ 1  2  3  4  5  6  7  8  9 10], and size = 10
 and shape = (10,)
Array1d = [ 1  2  3  4  5  6  7  8  9 10], and size = 10
 and shape = (2, 4)


# We can convert lists into numpy array if it uses int values

In [3]:
list1 = list(range(40))
array = np.array(list1)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

# Array indexing and slicing

In [4]:
numpy_array = np.arange(1,30,2)
print(numpy_array)
'''
np.zeros((2,2)) creates 2x2 array with zero values
np.ones((2,2)) creates 2x2 array with ones values
np.eyes(3) creates identity matrix with 3rows and 3 columns
'''
np.linspace(1,10,5) #Creates evenly spaces between 1 to 10 with 5 gap
print(numpy_array.size)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
15


In [5]:
reshaped_array = numpy_array.reshape(5,3)
print(reshaped_array)
Flattenarray = reshaped_array.flatten()
print(Flattenarray[0])

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]
 [25 27 29]]
1


In [6]:
Flattenarray[0:5]

array([1, 3, 5, 7, 9])

In [7]:
Flattenarray[::-1] #Reverse Array
#We don't need loops for array it can perform vectorized operations
# Slicing return view it doesn't return copy

array([29, 27, 25, 23, 21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [8]:
SliceB = Flattenarray[3:7]
SliceB

array([ 7,  9, 11, 13])

In [11]:
SliceB[0] = 655
#Copy array can also make changes in original array 

print(f"Original Array : {Flattenarray}")
print(f"sliced Array of flatten array : {SliceB}")

Original Array : [  1   3   5 655   9  11  13  15  17  19  21  23  25  27  29]
sliced Array of flatten array : [655   9  11  13]


# slice is view and it affects original memory location 
- that's wny we have to use the .copy() method to create copy of an array in numpy

In [12]:
b = Flattenarray[0:5].copy()
b[0] = 67


print(f"Orignal Array: {Flattenarray}")
print(f"sliced view array : {SliceB}")
print(f"Copy array of original : {b}")

Orignal Array: [  1   3   5 655   9  11  13  15  17  19  21  23  25  27  29]
sliced view array : [655   9  11  13]
Copy array of original : [ 67   3   5 655   9]


In [13]:
arr = np.array([1,58,5,5,82,6,55,45])
arr[[1,4,6]]

array([58, 82, 55])

In [14]:
arr[arr>30]

array([58, 82, 55, 45])