# Exercises for Practice
- Create a 3×3 array filled with random numbers and print its shape.
- Convert an array of floats [1.1, 2.2, 3.3] into integers.
- Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
- Reshape a 1D array of size 9 into a 3×3 matrix.
- Use boolean masking to filter numbers greater than 50 in an array.

In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Array 3x3 = {arr} and \n it's shape {arr.shape}")

Array 3x3 = [[1 2 3]
 [4 5 6]
 [7 8 9]] and 
 it's shape (3, 3)


- Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [4]:
array = np.array([[1.1, 2.2, 3.3]], dtype=np.int64)
array


array([[1, 2, 3]])

- Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [5]:
array = np.array([1,2,3,4,5,6])
print(f"even numbers in array  = {array[array%2==0]}")

even numbers in array  = [2 4 6]


- Reshape a 1D array of size 9 into a 3×3 matrix.

In [6]:
array1d = np.arange(1,10)
print(array1d)
reshaped = array1d.reshape(3,3)
print(f"reshaped array = {reshaped}")

[1 2 3 4 5 6 7 8 9]
reshaped array = [[1 2 3]
 [4 5 6]
 [7 8 9]]


- Use boolean masking to filter numbers greater than 50 in an array.

In [7]:
array = np.arange(40,101,3)
print(array)
condition = array > 50
print("After boolean masking")
print(array[condition])

[ 40  43  46  49  52  55  58  61  64  67  70  73  76  79  82  85  88  91
  94  97 100]
After boolean masking
[ 52  55  58  61  64  67  70  73  76  79  82  85  88  91  94  97 100]


- multidimensional indexing

In [8]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
row1 = (np.sum(arr, axis=1)) #count elemets sum row wise
print(row1)

[ 6 15 24]


In [12]:
column1 = (np.sum(arr, axis=0)) #count elemets sum column wise
print(column1)
print(arr[0:3, 1:])

[12 15 18]
[[2 3]
 [5 6]
 [8 9]]
